### PR TITLE
Adds snippets for common jasmine functions

### PR DESCRIPTION
**Pull request by guilhermejcgois**
I've created some snippets for common jasmine functions (that help us a lot at work), can you merge and update the package please? If have someone that I need to do before, let me now please!

Regards

### CODE REVIEW

**Comment by GregOnNet** [comment]
Hey @guilhermejcgois,

many thanks for you PR.
I will prepare a new release today.

Kinds
Greg

**Comment by guilhermejcgois** [comment]
Great! Thanks @GregOnNet!!

**Comment by GregOnNet** [comment]
Hi,

ich have some trouble publishing the package right now.
It seems that apm was not made to be used with cmd oder cygwin on windows.

I work on a solution.

**Comment by GregOnNet** [comment]
🚀 https://github.com/GregOnNet/atom-angular-2-typeScript-snippets/releases

Thanks @guilhermejcgois 👍

**Pull request merged**
